#!/bin/sh
set -u
set -e
# Example init script, this can be used with nginx, too,
# since nginx and unicorn accept the same signals

# Feel free to change any of the following variables for your app:
APP_ROOT=/var/www/mtg/current/
PID=$APP_ROOT/tmp/pids/unicorn.pid
CMD='/usr/bin/bundle exec /usr/bin/unicorn -D -E production -c config/unicorn.rb'

old_pid="$PID.oldbin"

cd $APP_ROOT || exit 1

sig () {
test -s "$PID" && kill -$1 `cat $catPID`
}

oldsig () {
test -s $old_pid && kill -$1 `cat $old_pid`
}

case $1 in
start)
sig 0 && echo >&2 "Already running" && exit 0
$CMD
;;runningstop)sig QUIT && exit 0
echo >&2 "Not running"
;;
force-stop)
sig TERM && exit 0
echo >&2 "Not running"
;;
restart)
sig USR2 && exit 0
echo >&2 "Couldn't upgrade, starting '$CMD' instead"
$CMD
;;
rotate)
        sig USR1 && exitcho rotated logs OK && exit 0
        echo >&2 "Couldn't rotate logs" && exit 1
        ;;
*)
echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|forcece-stop>"
exit 1
;;
esac
